pretranslate:
  segments:
    ignore_patterns:
    - "{%\s?([a-zA-Z'\"\s]*)\s?%}"
    - "{%\s?Aside\s?('[a-z]+')?\s?%}"
    - "Native"
    - "^(title|authors|date|description): "

  paths:
  - source: "src/site/content/en"
    include:
    - "src/site/content/en/angular/**/index.md"
